# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://tkralphs.github.io

title : Ted Ralphs

author:
  name: Ted Ralphs
  email: ted@lehigh.edu
  github: tkralphs
  twitter: TedRalphs
  googleplus: +TedRalphs
  bio: "Possibly useful rambling about Software, Optimization, and other Miscellany"
  pic: http://coral.ie.lehigh.edu/~ted/files/images/Me10_small.JPG

gems:
  - jekyll-asciidoc

asciidoc: asciidoctor
asciidoc_ext: adoc
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style